#!/bin/bash

# Ensure output folder exists
mkdir -p task1

# Run Verilator to generate C++ model and Makefile
verilator -Wall --cc --trace counter_async.sv --exe counter_tb_async.cpp

# Build the simulation executable generated by Verilator
make -j -C obj_dir/ -f Vcounter_async.mk Vcounter_async

# Run the simulation (generates Vcounter_async.vcd)
./obj_dir/Vcounter_async

